import { test, expect } from '@playwright/test';

test('register', async ({ page }) => {
    const timestamp = Date.now();
    const email = 'testemail' + timestamp + '@fakeemail.com';

    await page.goto('https://nop-qa.portnov.com/register');
    await expect(page.getByRole('heading', { name: 'Register' })).toBeVisible();
    await page.getByRole('radio', { name: 'Male', exact: true }).check();
    await page.getByRole('textbox', { name: 'First name:' }).click();
    await page.getByRole('textbox', { name: 'First name:' }).fill('FirstTest');
    await page.getByRole('textbox', { name: 'Last name:' }).click();
    await page.getByRole('textbox', { name: 'Last name:' }).fill('LastTest');
    await page.locator('select[name="DateOfBirthDay"]').selectOption('6');
    await page.locator('select[name="DateOfBirthMonth"]').selectOption('7');
    await page.locator('select[name="DateOfBirthYear"]').selectOption('2000');
    await page.getByRole('textbox', { name: 'Email:' }).click();
    await page.getByRole('textbox', { name: 'Email:' }).fill(email);
    await page.getByRole('checkbox', { name: 'Newsletter:' }).uncheck();
    await page.getByRole('textbox', { name: 'Password:', exact: true }).click();
    await page.getByRole('textbox', { name: 'Password:', exact: true }).fill('12345Abc');
    await page.getByRole('textbox', { name: 'Password:', exact: true }).press('Tab');
    await page.getByRole('textbox', { name: 'Confirm password:' }).fill('12345Abc');
    await page.getByRole('button', { name: 'Register' }).click();
    await expect(page.getByRole('heading', { name: 'Register' })).toBeVisible();
    await expect(page.getByText('Your registration completed')).toBeVisible();
    await page.getByRole('link', { name: 'Continue' }).click();
    await expect(page.getByRole('heading', { name: 'Welcome to our store' })).toBeVisible();
});


test('test', async ({ page }) => {
    await page.goto('https://nop-qa.portnov.com/');
    await page.getByRole('link', { name: 'Computers' }).click();
    await page.getByRole('link', { name: 'Desktops' }).first().click();
    await page.getByRole('link', { name: 'Build your own computer', exact: true }).click();
    await page.locator('#product_attribute_2').selectOption('3');
    await page.getByRole('radio', { name: '320 GB' }).check();
    await page.waitForTimeout(1000);
    await page.locator('#add-to-cart-button-1').click();
    //await page.getByText('The product has been added to').click();
    await page.getByRole('link', { name: 'Shopping cart (0)' }).click();
    await expect(page.getByRole('heading', { name: 'Shopping cart' })).toBeVisible();
    await page.getByRole('checkbox', { name: 'I agree with the terms of' }).check();
    await page.getByRole('button', { name: 'Checkout' }).click();
    await expect(page.getByRole('heading', { name: 'Welcome, Please Sign In!' })).toBeVisible();
    await page.getByRole('button', { name: 'Checkout as Guest' }).click();
    await page.getByRole('textbox', { name: 'First name:' }).click();
    await page.getByRole('textbox', { name: 'First name:' }).fill('TestFirst');
    await page.getByRole('textbox', { name: 'First name:' }).press('Tab');
    await page.getByRole('textbox', { name: 'Last name:' }).fill('TestLast');
    await page.getByRole('textbox', { name: 'Last name:' }).press('Tab');
    await page.getByRole('textbox', { name: 'Email:' }).fill('email842376238@ttt.com');
    await page.getByRole('textbox', { name: 'Email:' }).press('Tab');
    await page.getByRole('textbox', { name: 'Company:' }).press('Tab');
    await page.getByLabel('Country:').selectOption('237');
    await page.getByLabel('State / province:').selectOption('1677');
    await page.getByRole('textbox', { name: 'City:' }).click();
    await page.getByRole('textbox', { name: 'City:' }).fill('Sunnyvale');
    await page.getByRole('textbox', { name: 'Address 1:' }).click();
    await page.getByRole('textbox', { name: 'Address 1:' }).fill('123 Main St');
    await page.getByRole('textbox', { name: 'Zip / postal code:' }).click();
    await page.getByRole('textbox', { name: 'Zip / postal code:' }).fill('94000');
    await page.getByRole('textbox', { name: 'Phone number:' }).click();
    await page.getByRole('textbox', { name: 'Phone number:' }).fill('12345');
    await page.getByRole('button', { name: 'Next' }).click();
    await expect(page.getByRole('heading', { name: 'Select shipping method' })).toBeVisible();
    await page.getByRole('radio', { name: 'Next Day Air ($0.00)' }).check();
    await page.getByRole('button', { name: 'Next' }).click();
    await page.getByRole('button', { name: 'Next' }).click();
    await expect(page.getByRole('heading', { name: 'Payment information' })).toBeVisible();
    await expect(page.locator('#shopping-cart-form')).toContainText('$1,315.00');
    await page.getByRole('button', { name: 'Next' }).click();
    await expect(page.getByRole('heading', { name: 'Confirm your order' })).toBeVisible();
    await expect(page.locator('#shopping-cart-form')).toContainText('$1,315.00');
    await page.getByRole('button', { name: 'Confirm' }).click();
    await expect(page.getByRole('heading', { name: 'Thank you' })).toBeVisible();
    await expect(page.getByText('Your order has been')).toBeVisible();
    await expect(page.getByText('Order number:')).toBeVisible();
    await page.getByRole('button', { name: 'Continue' }).click();
    await expect(page.getByRole('heading', { name: 'Welcome to our store' })).toBeVisible();
});
